### ISSUE TITLE
IPP Everywhere Self-Cert Tool Issue with Roll Media

### ISSUE THREAD

**Issue by syoungatcda** [istopwg/ippeveselfcert#94] opened 2022-07-27 16:32 UTC
Canon’s Large Format Printer with Roll-fed media fails with IPP Everywhere Self-Cert Tool 1.1 Update3 (in I-10 Get-Printer-Attributes Operation Test).  Self-Cert Tool expects media-ready="roll_current_609.6x0.0mm“ and our printer is returning "roll_current_609.6x0mm”.
According to PWG 5101.1 in 5.1 Media Size Self-Describing Name Format, a long-dim value of 0 is used for reporting the width of roll-fed media. [long-dim = dim / "0"]  So, "roll_current_609.6x0mm” should be accepted.  Please fix it in IPP Everywhere Self-Cert Tool 1.1.

The Error Message we got from IPP Everywhere Self-Cert Tool 1.1 is:
Error Message:
EXPECTED: media-ready WITH-ALL-VALUES /^(choice(_((custom|na|asme|roc|oe|roll)_[a-z0-9][-a-z0-9]*_([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])x([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])in|(custom|iso|jis|jpn|prc|om|roll)_[a-z0-9][-a-z0-9]*_([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])x([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])mm)){2,}|(custom|na|asme|roc|oe|roll)_[a-z0-9][-a-z0-9]*_([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])x([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])in|(custom|iso|jis|jpn|prc|om|roll)_[a-z0-9][-a-z0-9]*_([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])x([1-9][0-9]*(.[0-9]*[1-9])?|0.[0-9]*[1-9])mm)$/
        GOT: media-ready="na_letter_8.5x11in" 
        GOT: media-ready="roll_current_609.6x0mm"

**Comment by michaelrsweet** [comment] 2022-08-08 21:30
Dupe of #93.

**Closed by michaelrsweet** 2022-08-08 21:30 UTC
Labels: duplicate
